import config
import psycopg2
import psycopg2.extras

try:
    with psycopg2.connect(
            host=config.hostname,
            dbname=config.database,
            user=config.admin_name,
            password=config.password,
    ) as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            def create_all_clients_db():
                with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                    command = ''
                    create_script = '''
                            CREATE TABLE IF NOT EXISTS all_requests (
                            id INT GENERATED BY DEFAULT AS IDENTITY 
                            (START WITH 1 INCREMENT BY 1),
                            login varchar,
                            phone varchar,
                            department varchar,
                            manager varchar,
                            date date,
                            time time,
                            PRIMARY KEY (ID)
                            );
                        '''
                    cur.execute(create_script)
                    cur.execute('SELECT * FROM all_requests')
                    conn.commit()


            def add_request(user_array_info):
                with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                    login, phone, department, manager, date, time = user_array_info[0], user_array_info[1], \
                                                                    user_array_info[2], user_array_info[3], \
                                                                    user_array_info[4], user_array_info[5]
                    insert_script = 'INSERT INTO all_requests (login, phone, department, manager, date, time) VALUES (%s, %s, %s, %s, %s, %s)'
                    cur.execute(insert_script, (login, phone, department, manager, date, time))
                    print(f'{login} request added')
                    conn.commit()


            def is_user_in_db(username):
                with conn.cursor() as cur:
                    existence_script = f"SELECT name FROM all_requests WHERE name = '{username}'"
                    cur.execute(existence_script)
                    userlist = []
                    for i in cur:
                        userlist.append(i)
                    if userlist:
                        return True
                    else:
                        return False


            def get_status(username):
                with conn.cursor() as cur:
                    get_status_script = f"SELECT status FROM all_requests WHERE name = {username}"
                    cur.execute(get_status_script)
                    print(cur)


            def export_to_excel():
                with conn.cursor() as cur:
                    script = 'SELECT * FROM all_requests'
                    SQL_for_file_output = "COPY ({0}) TO STDOUT WITH CSV HEADER".format(script)
                    t_path_n_file = "C:\\Users\\Али\\PycharmProjects\\botv1\\db\\requests_file.csv"
                    try:
                        with open(t_path_n_file, 'w') as f_output:
                            cur.copy_expert(SQL_for_file_output, f_output)
                            print('DONE')
                    except psycopg2.Error as e:
                        t_message = "Error: " + e + "/n query we ran: " + script + "/n t_path_n_file: " + t_path_n_file
                        return 'DB ERROR'


except Exception as error:
    print(error)
