import config
import psycopg2
import psycopg2.extras

try:
    with psycopg2.connect(
            host=config.hostname,
            dbname=config.database,
            user=config.admin_name,
            password=config.password,
    ) as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            def create_managers_db():
                with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                    command = ''
                    create_script = '''
                            CREATE TABLE IF NOT EXISTS all_managers(
                            id INT GENERATED BY DEFAULT AS IDENTITY 
                            (START WITH 1 INCREMENT BY 1),
                            requests_amount int,
                            tg_name varchar,
                            PRIMARY KEY (ID)
                            );
                        '''
                    cur.execute(create_script)
                    cur.execute('SELECT * FROM all_managers')
                    conn.commit()
                    for i in get_manager_tg_names():
                        config.manager_shortnames.append(i)
                    print(config.manager_shortnames)


            def add_manager(manager_name):
                with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                    print(type(manager_name))
                    adding_script = "INSERT INTO all_managers (tg_name) VALUES (%s);"
                    cur.execute(adding_script, (manager_name,))
                    conn.commit()
                    print('OKKK')


            def get_manager_tg_names():
                with conn.cursor() as cur:
                    managers = []
                    select_script = 'SELECT tg_name FROM all_managers;'
                    cur.execute(select_script)
                    for i in cur:
                        managers.append(i[0])
                    return managers

            def export_to_excel():
                with conn.cursor() as cur:
                    script = 'SELECT * FROM all_managers'
                    SQL_for_file_output = "COPY ({0}) TO STDOUT WITH CSV HEADER".format(script)
                    t_path_n_file = "C:\\Users\\Али\\PycharmProjects\\botv1\\db\\manager_file.csv"
                    try:
                        with open(t_path_n_file, 'w') as f_output:
                            cur.copy_expert(SQL_for_file_output, f_output)
                    except psycopg2.Error as e:
                        t_message = "Error: " + e + "/n query we ran: " + script + "/n t_path_n_file: " + t_path_n_file
                        return 'DB ERROR'
except Exception as error:
    print(error)
