import config
import psycopg2
import psycopg2.extras

try:
    with psycopg2.connect(
            host=config.hostname,
            dbname=config.database,
            user=config.admin_name,
            password=config.password,
    ) as conn:
        with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
            def create_new_clients_db():
                with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                    command = ''
                    create_script = '''
                            CREATE TABLE IF NOT EXISTS new_clients(
                            id INT GENERATED BY DEFAULT AS IDENTITY 
                            (START WITH 1 INCREMENT BY 1),
                            date date,
                            full_name varchar,
                            phone varchar,
                            email varchar,
                            company varchar,
                            manager varchar,
                            PRIMARY KEY (ID)
                            );
                        '''
                    cur.execute(create_script)
                    cur.execute('SELECT * FROM new_clients')
                    conn.commit()


            def add_new_user(new_user_array_info):
                with conn.cursor(cursor_factory=psycopg2.extras.DictCursor) as cur:
                    print('start of add_new_user')
                    date, name, phone, email, company = new_user_array_info[0], new_user_array_info[1], \
                                                        new_user_array_info[2], new_user_array_info[3], \
                                                        new_user_array_info[4]
                    print(date, name, phone, email, company)
                    insert_script = 'INSERT INTO new_clients (date, full_name, phone, email, company) VALUES (%s, %s, %s, %s, %s)'
                    cur.execute(insert_script, (date, name, phone, email, company))
                    print('End of add_user')
                    print(f'{name} added')
                    conn.commit()


            def export_to_excel():
                with conn.cursor() as cur:
                    script = 'SELECT * FROM new_clients'
                    SQL_for_file_output = "COPY ({0}) TO STDOUT WITH CSV HEADER".format(script)
                    t_path_n_file = "C:\\Users\\Али\\PycharmProjects\\botv1\\db\\new_clients_file.csv"
                    try:
                        with open(t_path_n_file, 'w') as f_output:
                            cur.copy_expert(SQL_for_file_output, f_output)
                    except psycopg2.Error as e:
                        t_message = "Error: " + e + "/n query we ran: " + script + "/n t_path_n_file: " + t_path_n_file
                        return 'DB ERROR'


except Exception as error:
    print(error)
